# Generated by Django 4.1.4 on 2022-12-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_order_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(upload_to='qr_codes')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bike')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.station')),
            ],
        ),
    ]
