# Generated by Django 4.1.4 on 2022-12-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bike_station_order_bike_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='accounts.bike'),
        ),
    ]
