# Generated by Django 4.1.4 on 2022-12-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bike_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='qr_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
