# Generated by Django 4.1.4 on 2022-12-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bike_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='qr_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
