# Generated by Django 4.1.4 on 2022-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_bike_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='qrimg_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
