# Generated by Django 4.1.4 on 2022-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bike_qrimg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aut_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
